version: '3'
services:
  all-registry:
    image: registry:2
    container_name: all-registry
    restart: always
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - redis

  gcr-registry:
    image: registry:2
    container_name: gcr-registry
    restart: always
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
    ports:
      - 127.0.0.1:5001:5000
    environment:
      - REGISTRY_PROXY_REMOTEURL=https://k8s.gcr.io
    depends_on:
      - redis

  hub-registry:
    image: registry:2
    container_name: hub-registry
    restart: always
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
    ports:
      - 127.0.0.1:5002:5000
    environment:
      - REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io
    depends_on:
      - redis

  quay-registry:
    image: registry:2
    container_name: quay-registry
    restart: always
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
    ports:
      - 127.0.0.1:5003:5000
    environment:
      - REGISTRY_PROXY_REMOTEURL=https://quay.io
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
